# Generated by Django 3.0.5 on 2020-04-21 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 20, 49, 52, 922132, tzinfo=utc)),
        ),
    ]
